services:
  golf_bdd:
    container_name: golf_bdd
    image: mariadb:latest
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bddname
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5

  #golf_adminer:
   # container_name: golf_adminer
    #image: adminer
    #ports:
    #- 8080:8080

  golf_backend:
    container_name: golf_backend_build
    image: ghcr.io/louislucas64/bloc3devops-back:latest
    environment:
      BDD_HOST: golf_bdd
    ports:
      - 12000:12000
    depends_on:
      golf_bdd:
        condition: service_healthy

  golf_frontend:
    container_name: golf_frontend
    image: ghcr.io/louislucas64/bloc3devops-front:latest
    ports:
      - 80:80