name: 02-2_ - Deploy

on:
  workflow_call

jobs:
  AzureDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Update Compose File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          PORT: ${{ secrets.AZURE_PORT }}
          username: ${{ secrets.AZURE_LOGIN }}
          password: ${{ secrets.AZURE_PASSEWORD }} 

          source: "./docker-compose.yml"
          target: "."

      - name: Satrt app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          port: ${{ secrets.AZURE_PORT }}
          username: ${{ secrets.AZURE_LOGIN }}
          password: ${{ secrets.AZURE_PASSEWORD }} 

          script: |
            echo ${{secrets.MONOREPO}} | docker login ghcr.io -u LouisLucas64 --password-stdin
            docker pull ghcr.io/louislucas64/golfepad-back:latest
            docker pull ghcr.io/louislucas64/golfepad-front:latest

            docker compose up -d