name: 01 - Integration

on:
 # push:
  #  branches:
   #   - marcel

  pull_request:
    branches:
      - main

jobs:
  Test_Back_Front:
  #if: ${{ git.event_name== 'push && github.ref_name == 'develop' }}
  uses: ./.github/workflows/01-1_TestBackFront.yaml

  #Diplay_Data:
   # runs-on: ubuntu-latest
    #needs: [Test_Back_Front]
 #   steps:
 #     - name: Display Data
  #      run: znv | sort

  Quality_SonarQube:
    #if: ${{ github.event_name == 'pull_request'}}
    needs: [Test_Back_Front]
    uses: ./.github/workflows/01-2_SonarQube.yaml 
    secrets: inherit
    
  Security_Snyk:
    #if: ${{ github.event_name == 'pull_request'}}
    needs: [Quality_SonarQube]
    uses: ./.github/workflows/01-3_Snyk.yaml  
    secrets: inherit