name: 02 - Deploy

on:
  push:
    branches:
      - main

jobs:
  Dockerbuild:
    uses: ./.github/workflows/02-1DockerBuild.yaml
    secrets: inherit

  Deploy:
    needs: [Dockerbuild]
    uses: ./.github/workflows/02_2_Deploy.yaml
    secrets: inherit